recipe: default.v1
language: es

pipeline:
- name: SpacyNLP
  model: "es_core_news_md"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50
  constrain_similarities: true

policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20250526-195049-global-dust
